M48
; DRILL file KiCad 10.0.6 date 2026-10-04T16:43:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-04T16:43:45-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X86.605Y-96.11
X86.605Y-101.89
T2
X91.0Y-84.0
X179.5Y-84.0
M30
